import command as cmd
import input_output as io
from command import run_command

'''
performs a test for a given variational problem and mesh choice
Input values: 
- 'commit_a', 'commit_b': the commits (or branch names) across which the test will be done
- 'root_path': the root path, upstream of all paths
- 'mesh_path_a (b)': the path of the code which generates the mesh in commit a (b)
- 'code_path_a (b)': the path of the code which solves the variational problem in commit a (b)
- 'mesh_solution_path_a', 'problem_solution_path_a', 'mesh_solution_path_b', 'problem_solution_path_b': the parhs where the mesh and variational-problem solution will be stored, for commit_a and commit_b
- 'name_of_generate_mesh': the name of the code which generates the mesh, without '.py': for example: 'generate_square_mesh', 'generate_ring_mesh'...
- 'mesh_resolution': the resolution of the mesh generated to make the test
- 'problem': the name of the variational problem to be solved, for example, 'square_a', 'ring_2', ... 
- 'success': A list with only one boolean enty, whose first entry will be set to True (False) if all commands in the method call have run successfully or not, respectively. If success[0] = False, this method will do nothing and return False
Output values: 
- 'True' ('False') if all csv files generated by commit_a are the same as those generated by commit_b
'''
def test_problem_and_mesh(commit_a,
                          commit_b,
                          root_path,
                          mesh_path_a, code_path_a,
                          mesh_path_b, code_path_b,
                          mesh_solution_path_a, problem_solution_path_a,
                          mesh_solution_path_b, problem_solution_path_b,
                          name_of_generate_mesh, mesh_resolution,
                          problem,
                          success
                          ):

    if(success[0]):
        #this method has been called with a success variable previously set to True -> The previous checks have been performed with no errors -> Proceed with this check

        # checkout commit_a, generate the mesh and solve the problem
        cmd.checkout(commit_a, success)

        run_command(f'cd {mesh_path_a}; rm -rf {mesh_solution_path_a}; mkdir -p {mesh_solution_path_a}; python3 {name_of_generate_mesh}.py {mesh_resolution} {mesh_solution_path_a}', success)
        run_command(f'cd {code_path_a}; rm -rf {problem_solution_path_a}; mkdir -p {problem_solution_path_a}; python3 solve.py {problem} {mesh_solution_path_a} {problem_solution_path_a}', success)

        # checkout commit_b, generate the mesh and solve the problem
        cmd.checkout(commit_b, success)
        run_command(f'cd {mesh_path_b}; rm -rf {mesh_solution_path_b}; mkdir -p {mesh_solution_path_b}; python3 {name_of_generate_mesh}.py {mesh_resolution} {mesh_solution_path_b}', success)
        run_command(f'cd {code_path_b}; rm -rf {problem_solution_path_b}; mkdir -p {problem_solution_path_b}; python3 solve.py {problem} {mesh_solution_path_b} {problem_solution_path_b}', success)

        # compare the mesh and problem solution for commit_a and commit_b
        # mesh_check = cmd.command_empty_err_out(f'cd {root_path}; ./compare-csv-files.sh {mesh_solution_path_a} {mesh_solution_path_b}')
        output_mesh, error_mesh = run_command(f'cd {root_path}; ./compare-csv-files.sh {mesh_solution_path_a} {mesh_solution_path_b}', success)
        mesh_check = (((output_mesh.strip() == "")) and ((error_mesh.strip() == "")))

        # problem_check = cmd.command_empty_err_out(f'cd {root_path}; ./compare-csv-files.sh {problem_solution_path_a} {problem_solution_path_b}')
        output_problem, error_problem = run_command(f'cd {root_path}; ./compare-csv-files.sh {problem_solution_path_a} {problem_solution_path_b}', success)
        problem_check = (((output_problem.strip() == "")) and ((error_problem.strip() == "")))


        # if check = true, then commit_a and commit_b give the same result
        check = (success[0] and mesh_check and problem_check)

        io.check_print(mesh_check, 'Mesh check OK', 'Mesh check NOT OK')
        io.check_print(problem_check, 'Problem check OK', 'Problem check NOT OK')

    else:
        #this method has been called with a success variable previously set to False -> The previous checks gave  errors -> Do not proceed with the check
        print('Stopping here.')
        check = False

    return check
