'''
This code checks the mesh generated by generate_two_squares_no_circle_mesh a

Run with
    clear; clear; python3 check_mesh_two_squares_no_circle.py [path where to find the mesh]
Example:
    clear; clear; python3 check_mesh_two_squares_no_circle.py solution
'''

import sys

# add the path where to find the shared modules
module_path = '/home/fenics/shared/modules'
sys.path.append(module_path)

import load_mesh as lmsh
import mesh as msh
import read_mesh_two_squares_no_circle as rmsh


import check_mesh_tags_two_squares_no_circle
msh.check_mesh_symmetry(lmsh.mesh, [rmsh.L/2, rmsh.h/2])

